"use client";

import "./globals.scss";
import { Inter } from "next/font/google";
import { ParallaxProvider } from "react-scroll-parallax";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ParallaxProvider>
        <body className={inter.className}>{children}</body>
      </ParallaxProvider>
    </html>
  );
}
